/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jvhjxaaemqlwksptrdsz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2aGp4YWFlbXFsd2tzcHRyZHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNDQ5MzAsImV4cCI6MjA4NzcyMDkzMH0.0_MFvxxhfkuzMp8K1jS5UNvV-j0XoE09v8sd-CwmFHc"